version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-ecr: circleci/aws-ecr@9.1.0

workflows:
  version: 2
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                profile_name: docent-splitted-deploy
          region: eu-west-3
          dockerfile: Dockerfile
          profile_name: docent-splitted-deploy
          repo: docent-splitted/docent-llm-service
          filters:
            branches:
              only:
                - main